<?php
session_start();

/* ================= AUTH ================= */
if (!isset($_SESSION['user_id'])) {
    header("Location: ../auth/login.php");
    exit;
}

include "../db.php";
include "../engine/prescription_engine.php";

/* ================= LOAD FPDF ================= */
require_once __DIR__ . '/../fpdf/fpdf.php';
if (!class_exists('FPDF')) {
    die("FPDF library not loaded");
}

/* ================= SESSION USER ================= */
$patient_id = (int) $_SESSION['user_id'];

/* ================= FETCH PATIENT ================= */
$pq = mysqli_query(
    $conn,
    "SELECT name, region FROM patient WHERE patient_id = $patient_id"
);

if (!$pq || mysqli_num_rows($pq) === 0) {
    die("Patient record not found");
}

$patient = mysqli_fetch_assoc($pq);

/* ================= FETCH DISEASE HISTORY ================= */
$q = mysqli_query($conn, "
    SELECT d.disease_name, h.detected_date, h.status, h.severity_level
    FROM patient_disease_history h
    JOIN disease_master d ON h.disease_id = d.disease_id
    WHERE h.patient_id = $patient_id
    ORDER BY h.detected_date DESC
");

/* ================= CREATE PDF ================= */
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 15);

/* ================= TITLE ================= */
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,12,'HealthIntel - Medical Report',0,1,'C');
$pdf->Ln(3);

/* ================= PATIENT INFO ================= */
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Patient Name: '.$patient['name'],0,1);
$pdf->Cell(0,8,'Region: '.$patient['region'],0,1);
$pdf->Ln(5);

/* ================= DISEASE DETAILS ================= */
if ($q && mysqli_num_rows($q) > 0) {

    while ($row = mysqli_fetch_assoc($q)) {

        /* GET PRESCRIPTION SAFELY */
        $pres = getPrescription($row['disease_name']) ?? [
            'medicines' => [],
            'advice' => [],
            'followup' => 'Follow doctor recommendations.'
        ];

        /* DISEASE TITLE */
        $pdf->SetFont('Arial','B',13);
        $pdf->Cell(0,10,$row['disease_name'],0,1);

        /* BASIC DETAILS */
        $pdf->SetFont('Arial','',11);
        $pdf->Cell(0,7,'Detected Date: '.$row['detected_date'],0,1);
        $pdf->Cell(0,7,'Status: '.$row['status'],0,1);
        $pdf->Cell(0,7,'Severity: '.$row['severity_level'],0,1);
        $pdf->Ln(2);

        /* PRESCRIPTION */
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(0,8,'Prescription:',0,1);
        $pdf->SetFont('Arial','',11);

        if (!empty($pres['medicines'])) {
            foreach ($pres['medicines'] as $m) {
                $pdf->MultiCell(0,7,'- '.$m);
            }
        } else {
            $pdf->MultiCell(0,7,'- No medicines listed');
        }

        $pdf->Ln(2);

        /* DOCTOR ADVICE */
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(0,8,'Doctor Advice:',0,1);
        $pdf->SetFont('Arial','',11);

        if (!empty($pres['advice'])) {
            foreach ($pres['advice'] as $a) {
                $pdf->MultiCell(0,7,'- '.$a);
            }
        } else {
            $pdf->MultiCell(0,7,'- No specific advice available');
        }

        $pdf->Ln(2);

        /* FOLLOW UP */
        $pdf->SetFont('Arial','B',11);
        $pdf->Cell(0,8,'Follow-up:',0,1);
        $pdf->SetFont('Arial','',11);
        $pdf->MultiCell(0,7,$pres['followup']);

        /* SEPARATOR */
        $pdf->Ln(5);
        $pdf->Cell(0,0,'',1);
        $pdf->Ln(6);
    }

} else {
    $pdf->SetFont('Arial','',11);
    $pdf->Cell(0,10,'No disease history found.',0,1);
}

/* ================= DISCLAIMER ================= */
$pdf->Ln(4);
$pdf->SetFont('Arial','I',9);
$pdf->MultiCell(
    0,
    6,
    "Disclaimer: This report and prescription are generated for academic and demonstration purposes only. 
They do not constitute real medical advice. Always consult a licensed medical professional."
);

/* ================= FOOTER ================= */
$pdf->Ln(5);
$pdf->Cell(0,8,'Generated by HealthIntel',0,1,'C');

/* ================= OUTPUT ================= */
$pdf->Output('D', 'HealthIntel_Medical_Report.pdf');
exit;
